# Generated by Django 4.1 on 2022-08-07 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
