# Generated by Django 4.1 on 2022-08-18 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_reviews_options_rename_message_reviews_content_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
