# Generated by Django 4.1 on 2022-08-18 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='pr',
        ),
    ]
