# Generated by Django 4.1 on 2022-08-18 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_rename_post_comment_pr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='pr',
            new_name='post',
        ),
    ]
