# Generated by Django 4.1 on 2022-08-19 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_comment_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='prod',
        ),
    ]
